service:
  name: moocrec-admin-rest-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  environment: ${file(./.config/env.${self:provider.stage}.json)}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
